package com.company.syntaxAnalysis;

public enum Statement {

    GOAL,
    MAINCLASS,
    CLASSDECLARATION,
    VARDECLARATION,
    METHODDECLARATION,
    TYPE,
    STATEMENTS,
    IFSTATEMENT,
    WHILESTATEMENT,
    PRINTSTATEMENT,
    ASSIGNSTATEMENT,
    ARRAYSTATEMENT,
    STATEMENT,
    INTEXPRESSION,
    TRUEEXPRESSION,
    FALSEEXPRESSION,
    IDENTIFIEREXPRESSION,
    THISEXPRESSION,
    NEWARRAYEXPRESSION,
    NEWEXPRESSION,
    NOEXPRESSION,
    BRACEEXPREESION,
    EXPRESSION,
    OPL,
    EXPRESSIONL,
    LENGTHL,
    METHODL,
    NULLL,
    L

}
