package com.company.syntaxAnalysis;

/**
 * 语法树的状态
 *
 * @author jun
 * @version 1.0
 */
public enum Statement {

    GOAL,
    MAINCLASS,
    CLASSDECLARATION,
    VARDECLARATION,
    METHODDECLARATION,
    TYPE,
    STATEMENTS,
    IFSTATEMENT,
    WHILESTATEMENT,
    PRINTSTATEMENT,
    ASSIGNSTATEMENT,
    ARRAYSTATEMENT,
    STATEMENT,
    INTEXPRESSION,
    TRUEEXPRESSION,
    FALSEEXPRESSION,
    IDENTIFIEREXPRESSION,
    THISEXPRESSION,
    NEWARRAYEXPRESSION,
    NEWEXPRESSION,
    NOEXPRESSION,
    BRACEEXPREESION,
    EXPRESSION,
    OPL,
    EXPRESSIONL,
    LENGTHL,
    METHODL,
    NULLL,
    L

}
